### ISSUE TITLE
Emails are not sent regardless of configuration settings

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-statamic3#180]
Hola! 

I'm back and continuing to test things before launch. One bug that popped up was a problem with emails not being sent after a comment is made. I checked the settings and, yeah, a test email works within Statamic so that part is good. Email settings for Meerkat checkout. Regardless of whether the settings are set via the control panel or directly to the email.php file no emails are being sent. Bummer. :(

**Comment by JohnathonKoster** [comment]
I am having troubles reproducing this on the latest versions of Meerkat and Statamic. Do you have any configured spam guards that may be flagging the email as spam (if the Email "Check Spam" option is selected)?

Additionally Meerkat, by default, will attempt to delay as much processing as it can for performance, which doesn't always work on all systems (this is still an item under review). Creating a `config/meerkat/internals.php` file with the following content (this file is not automatically created when Meerkat is installed) has resolved this behavior on other setups:

```php
<?php

return [
    'runDelayedMutationsSync' => true
];
```

**Comment by jeffwhitfield** [comment]
Yeah, unfortunately, that didn't reveal anything. This is an instance that is being run locally using MAMP Pro. Lemme try throwing it onto one of my remote servers and see what happens. Could be the local instance is interfering with things. :P

**Comment by JohnathonKoster** [comment]
Interesting! Do you have the "auto delete spam" checkbox enabled, as well?

**Comment by jeffwhitfield** [comment]
Nope! But I uploaded the site to one of my servers and the problem is still there. I'm getting this in one of the log files:

```
[2021-02-19 00:37:42] local.ERROR: Call to a member function id() on null {"exception":"[object] (Error(code: 0): Call to a member function id() on null at /home/runcloud/webapps/velonut-dev/vendor/stillat/meerkat/src/Configuration/UserConfigurationManager.php:126)
[stacktrace]
#0 /home/runcloud/webapps/velonut-dev/vendor/stillat/meerkat/src/Configuration/UserConfigurationManager.php(77): Stillat\\Meerkat\\Configuration\\UserConfigurationManager->loadUserDetails()
#1 /home/runcloud/webapps/velonut-dev/vendor/stillat/meerkat/src/Statamic/ControlPanel/SettingsProvider.php(64): Stillat\\Meerkat\\Configuration\\UserConfigurationManager->getConfiguration()
#2 /home/runcloud/webapps/velonut-dev/vendor/stillat/meerkat/routes/emit.php(27): Stillat\\Meerkat\\Statamic\\ControlPanel\\SettingsProvider->emitStatements()
#3 /home/runcloud/webapps/velonut-dev/vendor/stillat/meerkat/src/Http/Emitter/Emit.php(107): Illuminate\\Routing\\RouteFileRegistrar->{closure}()
#4 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(230): Stillat\\Meerkat\\Http\\Emitter\\Emit::Stillat\\Meerkat\\Http\\Emitter\\{closure}()
#5 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(200): Illuminate\\Routing\\Route->runCallable()
#6 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Routing\\Route->run()
#7 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#10 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#12 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#14 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#16 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#17 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#19 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#21 /home/runcloud/webapps/velonut-dev/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Retrieve->handle()
#23 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Pipeline\\Pipeline->then()
#25 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\\Routing\\Router->runRouteWithinStack()
#26 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#27 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#28 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#29 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#30 /home/runcloud/webapps/velonut-dev/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#32 /home/runcloud/webapps/velonut-dev/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#34 /home/runcloud/webapps/velonut-dev/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#36 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#38 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#40 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#42 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#44 /home/runcloud/webapps/velonut-dev/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#46 /home/runcloud/webapps/velonut-dev/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#48 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#50 /home/runcloud/webapps/velonut-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#51 /home/runcloud/webapps/velonut-dev/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#52 {main}
"} 
```

**Comment by JohnathonKoster** [comment]
File request sent via. email.
