### ISSUE TITLE
Comment overview cannot find comments when a related article has been deleted

### ISSUE THREAD

**Issue by juliawarnke** [Stillat/meerkat-statamic3#204]
### The Problem
The comment overview `path: /admin/meerkat/all` cannot find any existing comments. At the same time the spinner at the top right won't stop spinning.
 
![Bildschirmfoto 2022-05-05 um 09 22 23](https://user-images.githubusercontent.com/44929138/166879934-5317e2b5-a61c-4a26-a5e4-334e9f0bf771.png)

Error message in the console:
```
Uncaught (in Promise) 

TypeError: Cannot read properties of null (reading 'contextId')
    at Function.value (http://scraft.localhost/vendor/meerkat/js/2.4.11/meerkat.min.js:2:251255)
    at Function.value (http://scraft.localhost/vendor/meerkat/js/2.4.11/meerkat.min.js:2:321270)
    at e.<anonymous> (http://scraft.localhost/vendor/meerkat/js/2.4.11/meerkat.min.js:2:325589)

```

### How to recreate the problem

1. Create an article
2. Create a comment for the article
3. Delete article

My Setup:
```
PHP 8.0
Meerkat 2.4.11
Statamic 3.2.39
```

**Comment by JohnathonKoster** [comment]
Should be resolved with 2.5.1 😊
